version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: flipflop-postgres
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  flipflop-indexer-devnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flipflop-indexer-devnet
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_DEVNET}
      MANIFEST: /app/flipflop-indexer-devnet-v0.1.0.spkg
      SUBSTREAMS_API_TOKEN: ${SUBSTREAMS_API_TOKEN_DEVNET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - ./:/app:ro
      - devnet-data:/var/lib/substreams
    restart: unless-stopped

  flipflop-indexer-mainnet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flipflop-indexer-mainnet
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME_MAINNET}
      MANIFEST: /app/flipflop-indexer-mainnet-v0.1.0.spkg
      SUBSTREAMS_API_TOKEN: ${SUBSTREAMS_API_TOKEN_MAINNET}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - ./:/app:ro
      - mainnet-data:/var/lib/substreams
    restart: unless-stopped

  # Graph server for devnet (PostGraphile)
  flipflop-graph-devnet:
    image: node:18-alpine
    container_name: flipflop-graph-devnet
    env_file:
      - .env
    environment:
      # 仅覆盖 DB_NAME，其他 DB_* 从 .env 继承
      DB_NAME: ${DB_NAME_DEVNET}
    depends_on:
      - postgres
      - flipflop-indexer-devnet
    command:
      [
        "sh", "-lc",
        "apk add --no-cache postgresql-client && \
         DB_DSN=\"postgres://$$DB_USER:$$DB_PASSWORD@$${DB_HOST:-postgres}:$${DB_PORT:-5432}/$${DB_NAME:-substreams}?sslmode=$${DB_SSLMODE:-disable}\" && \
         until pg_isready -h \"$${DB_HOST:-postgres}\" -p \"$${DB_PORT:-5432}\" -U \"$$DB_USER\" -d \"$${DB_NAME:-substreams}\"; do \
           echo 'waiting for postgres...'; sleep 2; \
         done && \
         echo \"postgres is ready at $${DB_HOST:-postgres}:$${DB_PORT:-5432}/$${DB_NAME:-substreams}\" && \
         psql \"$$DB_DSN\" -v ON_ERROR_STOP=1 -c \"COMMENT ON TABLE public.cursors IS E'@omit';\" || true && \
         npx --yes postgraphile \
           -n 0.0.0.0 --port $${GRAPH_PORT_DEVNET:-5051} \
           --schema public --enhance-graphiql --watch \
           -c \"$$DB_DSN\""
      ]
    ports:
      - "${GRAPH_PORT_DEVNET:-5051}:${GRAPH_PORT_DEVNET:-5051}"
    restart: unless-stopped

  # Graph server for mainnet (PostGraphile)
  flipflop-graph-mainnet:
    image: node:18-alpine
    container_name: flipflop-graph-mainnet
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME_MAINNET}
    depends_on:
      - postgres
    command:
      [
        "sh", "-lc",
        "apk add --no-cache postgresql-client && \
         DB_DSN=\"postgres://$$DB_USER:$$DB_PASSWORD@$${DB_HOST:-postgres}:$${DB_PORT:-5432}/$${DB_NAME:-substreams}?sslmode=$${DB_SSLMODE:-disable}\" && \
         until pg_isready -h \"$${DB_HOST:-postgres}\" -p \"$${DB_PORT:-5432}\" -U \"$$DB_USER\" -d \"$${DB_NAME:-substreams}\"; do \
           echo 'waiting for postgres...'; sleep 2; \
         done && \
         echo \"postgres is ready at $${DB_HOST:-postgres}:$${DB_PORT:-5432}/$${DB_NAME:-substreams}\" && \
         psql \"$$DB_DSN\" -v ON_ERROR_STOP=1 -c \"COMMENT ON TABLE public.cursors IS E'@omit';\" || true && \
         npx --yes postgraphile \
           -n 0.0.0.0 --port $${GRAPH_PORT_MAINNET:-5050} \
           --schema public --enhance-graphiql --watch \
           -c \"$$DB_DSN\""
      ]
    ports:
      - "${GRAPH_PORT_MAINNET:-5050}:${GRAPH_PORT_MAINNET:-5050}"
    restart: unless-stopped

volumes:
  postgres-data: {}
  devnet-data: {}
  mainnet-data: {}